### ISSUE TITLE
Error on malformed modelines

### ISSUE THREAD

**Issue by reedes** [reedes/vim-pencil#14]
Given:

```
<!-- vim: tw=65 -->
```

"50k/4.md" 26L, 641C
Error detected while processing modelines:
line   26:
E518: Unknown option: -->
Press ENTER or type command to continue

**Comment by alerque** [comment]
This is not an issue with Pencil, you're just using the wrong modeline format. Vim has a couple different formats available to accommodate different language's comment syntax nuances. For HTML (and hence Markdown) the modeline syntax you need to use is the "set surrounded by colons" format.

```markdown
<!-- vim: set tw=65: -->
```

As documented in `:help modeline` this variant better accommodates comment syntaxes that have closing values such as `*/` or `-->` that need to be excluded from the bit Vim parses.
