### ISSUE TITLE
Is it possible to add functionality to change font size? (enhancement)

### ISSUE THREAD

**Issue by whitesiroi** [reedes/vim-pencil#35]
Hello,

Just wanna say that I love using MacVim as word processor with your plugins like thematic, vim-colors-pencil, vim-pencil, ... It'll be superb to change font size :) Is it possible to have multiple font sizes in the same file?

Thank you & best regards,
Artem

**Comment by reedes** [comment]
Only one font size as far as I know. That's a limitation of Vim.

Glad to hear you find the plugins useful!

**Comment by whitesiroi** [comment]
Thank you very much for your reply.

>> Glad to hear you find the plugins useful!
Thanks to you I moved from Mac's word processors to MacVim ^^
Again, thank you & have an awesome day ^^
