### ISSUE TITLE
Custom abberviations no longer work when Pencil is loaded

### ISSUE THREAD

**Issue by Battleroid** [reedes/vim-pencil#36]
Hello,

I have a small list of custom insert mode abbreviations for some unicode symbols, however, whenever I edit a filetype that Pencil is called for they appear to no longer function. If I check `:ab` they appear to be loaded though.

I'm also using Litecorrect however disabling that does not yield any difference. Disabling Pencil fixes the issue (but I obviously don't want that :-))

Is there anything I should be doing different to prevent this?

**Comment by Battleroid** [comment]
I ended up just removing the abbreviations and using the digraphs abbreviations instead since they're straightforward.

**Comment by reedes** [comment]
I can't find the issue, but another user was reporting problems with abbreviations after remapping the space key.

Pencil should work fine with abbreviations in any case, whether litecorrect or your custom ones. If not, there's an odd bug present.

**Comment by mrrcollins** [comment]
I'm seeing this problem with my setup. Abbreviations work when I comment out Pencil. 

My setup is available at https://github.com/mrrcollins/vim

I'll push my current .vimrc up, maybe I'm just missing something easy...
