### ISSUE TITLE
Typing below one line jumps it up to the one above it unless there is a line break between

### ISSUE THREAD

**Issue by jondkinney** [reedes/vim-pencil#46]
Maybe this is standard functionality? Seems like something funky is going on though... being able to type two lines without spaces between them is hopefully an option? To repro: if I'm making a list in markdown, for example, when I type one entry, hit enter and start to type the next bullet or dash immediately below the line above it (with no space in between), then it jumps up to the previous line. 

Is there a setting to stop that? Or is one of my other plugins messing with me?

![image](https://s3.amazonaws.com/f.cl.ly/items/310z382J1I2U0a0r1X35/Screen%20Recording%202016-06-17%20at%2012.00%20PM.gif)

Thanks!!

**Comment by reedes** [comment]
This is a known problem as described in #31.

There's some interaction between auto-format and the syntax plugin we don't yet understand.

Closing in favor of #31.
