### ISSUE TITLE
Pencil Mode breaks remapped movement keys

### ISSUE THREAD

**Issue by dangerginger** [reedes/vim-pencil#49]
I remapped my movement keys from `hjkl` to `jkl;`.  When I turn on pencil mode it is hard-coded to set `j` to `gj` (down) and `k` to `gk` (up). 

Ideally, the plugin would remap the currently used movement keys for up/down to `gj` and `gk`.

**Comment by reedes** [comment]
Great idea. I'll get to this in the near future.

**Comment by stu-b-doo** [comment]
any update on this? I like the concept of vim pencil but am currently struggling to use it because of this issue. Like @dangerginger I;ve got movement keys mapped to jkl;

**Comment by stu-b-doo** [comment]
okay, I made this change https://github.com/reedes/vim-pencil/pull/50/commits/341403d115c088121a42ff1fc23521bf3a6a6ee1 to my local version of pencil.vim and I like it!
