### ISSUE TITLE
Bold and Italic not working

### ISSUE THREAD

**Issue by pdoak** [reedes/vim-pencil#56]
## Environment

> Mac OSX 10.12.3
> iTerm: Build 3.1.20170221-nightly
> tmux: stable 2.3 (bottled), HEAD
> Plugins: tpope/vim-markdown
> Font: Cousine for Powerline
> Colorscheme: base16-tomorrow-night
> iTerm/Profiles/Text: Text Rendering - Italic text allowed

This is what I get:
![image](https://cloud.githubusercontent.com/assets/1565586/23253394/40c6caea-f9ac-11e6-9287-da78666daa95.png)

The Cousine for Powerline font has Regular, Italic, bold and bold italic and if I change the font in iTerm preferences to Italic or bold or bold italic, I see the change in vim with the correct font. e.g. Italic looks like this:
![image](https://cloud.githubusercontent.com/assets/1565586/23253617/1d238f82-f9ad-11e6-94dc-7fa009170412.png)

What else do I need to do to get it working properly?

**Comment by reedes** [comment]
Apart from enabling the conceal feature, pencil itself isn't involved in showing bold/italic in gui or terminal Vim.

Showing bold or italic in terminal Vim is some combination of using a font with bold/italic variations, a colorscheme that supports 'cterm' attributes, a syntax which maps to the bold/italic highlights, and configuring the terminal. As I use MacVim mostly, I'm afraid I'm of little help.

If you do get it working, please post a solution here.

**Comment by alerque** [comment]
As noted above, this is not going to be an issue with Pencil. I typically use the `vim-pandoc` filetype and hence the `vim-pandoc-syntax` syntax, but I just tested tpope's Markdown and it seems to support bold as well. I'm guessing this is going to be an issue with your colorscheme.

Let us know if there is anything this plugin can do...
