### ISSUE TITLE
Join lines `J` — does not reformat text below

### ISSUE THREAD

**Issue by oluckyman** [reedes/vim-pencil#59]
![](http://g.recordit.co/n1CuZj3eJi.gif)

**Comment by reedes** [comment]
The only keys pencil redefines are for smoother navigation and undo, but not for reformatting.

This is to preserve the existing vim formatting behavior, where you have the option of enhancing it yourself. See the suggested 'Q' remapping in the readme for something which might meet your needs.

**Comment by oluckyman** [comment]
got it. thanks for your efforts!
