### ISSUE TITLE
Make autoformat conscious of soft like breaks in hard wrap mode?

### ISSUE THREAD

**Issue by kartik-ynwa** [reedes/vim-pencil#62]
I will use hyphens to show spaces for clarity. Assume the following is a Markdown document.

```markdown
Markdown-is-a-markup-language.--
:thinking:
```
When trying to do this, line 2 is autoformatted back to line 1 and the two whitespaces at the end of line 1 denoting a line break are removed.

Is there a fix to this?

Thanks for this wonderful plugin by the way.

**Comment by reedes** [comment]
Hmm, a few ideas...

Use 'soft' mode which avoids Vim's aggressive autoformat.

With 'hard' mode, use the temporary method of disabling autoformat as described in the readme.

Precede ':thinking:' with a '- ' to treat it as a list, using Tim Pope's syntax (which is also default one)

Glad to see you like the plugin!

**Comment by kartik-ynwa** [comment]
I feel the best solution to this is to turn off autoformatting (`set fo-=a`) while allowing line breaks when `textwidth` is exceeded (`set fo+=t'). Autoformatting is gimmicky anyway. Autoformatting is gimmicky anyway.
