### ISSUE TITLE
How to soft wrap at 80 columns instead of the window size

### ISSUE THREAD

**Issue by triplekiller** [reedes/vim-pencil#64]
I want to use Vim's soft wrap capability (:set wrap) to wrap some code at 80 characters, regardless of my actual window width. Does vim-pencil achieve this? Thanks.

**Comment by matt-snider** [comment]
Hi @triplekiller, 

I also expected soft wrap to behave this way. That also seems to be the case [here](https://github.com/reedes/vim-pencil/issues/51).

Anyways, I found a good way to do this with `:set columns=80`. [vim-goyo](https://github.com/junegunn/goyo.vim) might also be useful.

**Comment by reedes** [comment]
Generally speaking, Pencil focuses on behavior rather that appearance. My other old plugin, Thematic, is where I added column support, such as to have generous margins in fullscreen mode in MacVim.
