### ISSUE TITLE
Go to end of line in insert mode using :SoftPencil 

### ISSUE THREAD

**Issue by nanangarsyad** [reedes/vim-pencil#67]
I already tried to find the related issues or thread about this but no luck, so Sorry, if I do repost.
My question is how to go to end of line of the current line in SoftPencil. Becuase If I press `end` button it'll bring me to the end of the paragraph instead.
If possible I wanted to go to end of line directly without having to press `<C-o>` and then press `<$>` in insert mode. 

Thank you.

**Comment by reedes** [comment]
Hmm, on my MacBook, I'm seeing that fn-right arrow gets me to the end of the line in both insert and normal mode.

What platform are you on? It could be that there's an issue of vim working differently.

**Comment by nanangarsyad** [comment]
Sorry for the late reply,

I'm on ubuntu using tmux with terminal-mode (`$TERM`) xterm-256color.
Yes, It was exactly like what you said, I'd tried by experimenting it with terminator, and the result is like what it should be.
By the why could you give me your thought why this bug happened when using `tmux` + `term=xterm-256color`?
Like the fact stated, tmux often had many kind of bugs with vim, but because the feature of tmux that irreplaceable I had no choice but to find a solution for each of the bug. So if you had any thought about this matter please let me know.

Thank you.

**Comment by alerque** [comment]
This should be fixed as of #82. The `$` key is now mapped to go to the end of the visual line, and `g$` to the true end of the line (paragraph if using soft wrap). These bindings seem to affect how `<home>` and `<end` are processed in insert mode as well. Of course the normal mode `<home>` and `<end>` bindings should do the same thing.

Please let me know if there is any further confusion in setting this up or any systems on which these don't work as expected.
